interface IConfig {
  VUE_APP_UNIVERSITY_NAME: string,
  VUE_APP_NAME: string,
  VUE_APP_SYSTEM_API: string,
  VUE_APP_CODE_API: string,
  VUE_APP_MODEL_API: string,
  VUE_APP_DOCUMENT_API: string,
  VUE_APP_MAINDATA_API: string,
  VUE_APP_METADATA_API: string,
  VUE_APP_DATAQUALITY_API: string,
  VUE_APP_DATAEXCHANGE_API: string,
  VUE_APP_SWOP_API: string,
  VUE_APP_DATAFILE_API: string,
  VUE_APP_MESSAGE_API: string,
  VUE_APP_SERVER_API: string,
  VUE_APP_DATASERVICE_API: string,
  VUE_APP_DATAASSETS_API: string,
  VUE_APP_MANAGEMENT_URL: string,
  VUE_APP_AUTH_TYPE: string,
  VUE_APP_AUTH_TYPE_LOGIN_URL: string,
  VUE_APP_AUTH_TYPE_CAS_URL: string,
  VUE_APP_NO_AUTH_SYSTEM_API: string,
  VUE_APP_PROCESSPLATFORM_URL: string,
  VUE_APP_STATISTICS_API: string,
  VUE_APP_DATA_SERVICE_API: string,
}
class Window {
  addEventListener = Function
  config: IConfig = {
    VUE_APP_UNIVERSITY_NAME: '树维大学',
    VUE_APP_NAME: '数据资产管理平台',
    VUE_APP_SYSTEM_API: 'http://ds.hf.supwisdom.com:81/gateway/api/agent/system',
    VUE_APP_CODE_API: 'http://ds.hf.supwisdom.com:81/gateway/api/agent/code',
    VUE_APP_MODEL_API: 'http://ds.hf.supwisdom.com:81/gateway/api/agent/model',
    VUE_APP_DOCUMENT_API: 'http://ds.hf.supwisdom.com:81/gateway/api/agent/document',
    VUE_APP_MAINDATA_API: 'http://ds.hf.supwisdom.com:81/gateway/api/agent/maindata',
    VUE_APP_METADATA_API: 'http://ds.hf.supwisdom.com:81/gateway/api/agent/metadata',
    VUE_APP_DATAQUALITY_API: 'http://ds.hf.supwisdom.com:81/gateway/api/agent/dataquality',
    VUE_APP_DATAEXCHANGE_API: 'http://ds.hf.supwisdom.com:81/gateway/api/agent/exchange',
    VUE_APP_SWOP_API: 'http://ds.hf.supwisdom.com:81/gateway/api/agent/swop',
    VUE_APP_DATAFILE_API: 'http://ds.hf.supwisdom.com:81/gateway/api/agent/datafile',
    VUE_APP_MESSAGE_API: 'http://ds.hf.supwisdom.com:81/gateway/api/agent/message',
    VUE_APP_SERVER_API: 'http://ds.hf.supwisdom.com:81/gateway/api/agent/datamonitor',
    VUE_APP_DATASERVICE_API: 'http://ds.hf.supwisdom.com:81/data-statistics',
    VUE_APP_DATAASSETS_API: 'http://ds.hf.supwisdom.com:81/data-assets',
    VUE_APP_MANAGEMENT_URL: 'http://ds.hf.supwisdom.com:81/dataassets/',
    VUE_APP_AUTH_TYPE: 'jwt',
    VUE_APP_AUTH_TYPE_LOGIN_URL: 'http://ds.hf.supwisdom.com:81/gateway/jwt/token/login',
    VUE_APP_AUTH_TYPE_CAS_URL: 'http://uniauth.paas.newcapec.cn/idtoken',
    VUE_APP_NO_AUTH_SYSTEM_API: 'http://ds.hf.supwisdom.com:81/data-system',
    VUE_APP_PROCESSPLATFORM_URL: '',
    VUE_APP_STATISTICS_API: 'http://ds.hf.supwisdom.com:81/gateway/api/agent/statistics',
    VUE_APP_DATA_SERVICE_API: "http://ds.hf.supwisdom.com:81/init/"
  }
}
export { Window }